# 금융 도메인 - 소비패턴 분석 시스템 설정
# Day 1 DDD 실습용 설정

spring:
  application:
    name: finance-demo
  
  # H2 데이터베이스 설정 (실습용)
  datasource:
    url: jdbc:h2:mem:financedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 콘솔 활성화 (실습 확인용)
  h2:
    console:
      enabled: true
      path: /h2-console

# 로깅 설정
logging:
  level:
    com.finance.demo: DEBUG
    org.springframework.context.event: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 서버 포트
server:
  port: 8080
